# Generated by Django 5.0 on 2024-01-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название жанра')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('release_date', models.DateField(verbose_name='Дата выхода')),
                ('stars_rating', models.IntegerField(verbose_name='Популярность')),
                ('genres', models.ManyToManyField(blank=True, null=True, to='movie.genre', verbose_name='Жанры')),
            ],
        ),
    ]
